name: CI build - sfos3.2 branch on SFOS 3.0.2.8 (armv7hl)

env:
  sfos_target: 3.0.2.8

on:
  push:
    tags:
      - 'v*-sfos3.2'
  pull_request:
    branches:
      - sfos3.2

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.sfos_target }}
        arch: armv7hl

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpm-build-result
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
